sudo: false
language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - peterkir
env:
# prepare pre-filled maven repository
install:
- wget https://s3-eu-west-1.amazonaws.com/klib.io/repoOomph.zip
#- wget http://klib.io/repoOomph.zip
- unzip -d $HOME repoOomph.zip
- echo "export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.repoOomph -Xmx2750m'" > ~/.mavenrc

script:
- DEFAULT_UPDATE_URL=http://peterkir.github.io/org.eclipse.oomph/$TRAVIS_BRANCH/repo/oomph
- echo patch the DEFAULT_UPDATE_URL to $DEFAULT_UPDATE_URL
- sed -i -e 's|http://download.eclipse.org/oomph/updates/milestone/latest|'$DEFAULT_UPDATE_URL'|g'
  plugins/org.eclipse.oomph.setup.core/src/org/eclipse/oomph/setup/internal/core/SetupCorePlugin.java
- mvn install --show-version --batch-mode --quiet --errors -P modules -DskipTests

after_success:
- BINTRAY_DESC=bintray.desc.json
- chmod a+x .travis-deploy.sh
- "./.travis-deploy.sh"
- sed -i -e 's|$DATE|'$DATE'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BRANCH|'$TRAVIS_BRANCH'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_JOB_NUMBER|'$TRAVIS_JOB_NUMBER'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BUILD_ID|'$TRAVIS_BUILD_ID'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BUILD_NUMBER|'$TRAVIS_BUILD_NUMBER'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_COMMIT|'$TRAVIS_COMMIT'|g' $BINTRAY_DESC
- cat $BINTRAY_DESC

deploy:
  on: nihalc
  provider: bintray
  file: bintray.desc.json
  user: nihalc
  key: ad9cf60527c55a217b2268f0552bde082061e40e
