sudo: false
language: java
jdk:
- oraclejdk7
branches:
  only:
  - master
  - peterkir
env:
  global:
  - secure: D5P0ufVcDSsP9+oeDLns1MGGgACe/Y8pc0oYNJtCEXrPkUJv3KdpTCnsdFuyYEygy9PDGBAYj/q+yTQNgj5IhnK6rohgnZ+Q4czMwk0oivhPaU2Ohx6o5enJFvy0CraOc7R0q+YwVSCnQv99ApSviMicOigfR3wsasY9UUOSNVDEoBWoP5j+A16Ts40g9XGUwbalZLxu5lcj+HAZ6vFwvp5M+YUmt3g0cBkVmuIfAsJgpYknTyYqFIDcmMnp3MWk1p1NgY9gzQ/XP4b28aBdFaZjLb+HsQ5vhIKhV/+jaeHnbzGHD7lqqJ0SxlxOYcgROfkK8NzfdyV/lhETCU661w5bl4nbrKylXlc+ngocDLgHzN4ovhxaG20HBvTmulAwFvcK8FbzmBOm+Y4DY//HyG/V4B5KX5TiKfUGAFk9iZ4DQLY4DA6o/CNRHzWTAVYrwl6Fhozgb2dZIZ1QMIOCmuIH2WvhjUBp2p99JFHbZ5QzANjIhmXz7q9qhwRWerurxCXBu7bWV9/6FTNflH04+OCOHzhpm65iA6GzchnR4fhlhHSVABFXHgL2jQ8iZNhHBIIM0JlHum68qE+fnTKTUmtTZNRebRm/ArONt0CwCcI88RSnBJpm/nflH7vF4ng2gpmrTKPsFAJyJFrU1BApwO/+gxZKd9iDeDZkrrk2pqo=
# prepare pre-filled maven repository
install:
- wget https://s3-eu-west-1.amazonaws.com/klib.io/repoOomph.zip
#- wget http://klib.io/repoOomph.zip
- unzip -d $HOME repoOomph.zip
- echo "export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.repoOomph -Xmx2750m'" > ~/.mavenrc

script:
- DEFAULT_UPDATE_URL=http://peterkir.github.io/org.eclipse.oomph/$TRAVIS_BRANCH/repo/oomph
- echo patch the DEFAULT_UPDATE_URL to $DEFAULT_UPDATE_URL
- sed -i -e 's|http://download.eclipse.org/oomph/updates/milestone/latest|'$DEFAULT_UPDATE_URL'|g'
  plugins/org.eclipse.oomph.setup.core/src/org/eclipse/oomph/setup/internal/core/SetupCorePlugin.java
- mvn install --show-version --batch-mode --quiet --errors -P modules -DskipTests

after_success:
- BINTRAY_DESC=bintray.desc.json
- chmod a+x .travis-deploy.sh
- "./.travis-deploy.sh"
- sed -i -e 's|$DATE|'$DATE'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BRANCH|'$TRAVIS_BRANCH'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_JOB_NUMBER|'$TRAVIS_JOB_NUMBER'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BUILD_ID|'$TRAVIS_BUILD_ID'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_BUILD_NUMBER|'$TRAVIS_BUILD_NUMBER'|g' $BINTRAY_DESC
- sed -i -e 's|$TRAVIS_COMMIT|'$TRAVIS_COMMIT'|g' $BINTRAY_DESC
- cat $BINTRAY_DESC

deploy:
  on: nihalc
  provider: bintray
  file: bintray.desc.json
  user: nihalc
  key: ad9cf60527c55a217b2268f0552bde082061e40e
